
server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice2_restaurants
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

security:
  jwt:
    key:
      private: ${jwtKey}
    user:
      generator: ${userGenerator}

